num=100
document.write (typeof num  +"<br>")
numb=73.9
document.write(typeof numb +"<br>");
document.write(typeof NaN  +"<br>")
document.write(typeof "water"  +"<br>")
document.write(typeof false  +"<br>")
document.write(typeof (9 != 11)  +"<br>")
document.write("Orang" + "e"  +"<br>")
document.write("Orange" - "s"  +"<br>") 
document.write("4" + "8"  +"<br>")
document.write("4" - "8"  +"<br>")
document.write("4" - "8"  +"<br>")
document.write("name" + 3  +"<br>")
document.write("name" - 3  +"<br>")
document.write(82 * "word"  +"<br>")
document.write(1 + "hello"  +"<br>")
document.write("hello" + 1  +"<br>")
document.write(1 + true  +"<br>")
document.write("hello" + true  +"<br>")
document.write( typeof (Infinity)  +"<br>" )
document.write(1 == '1'  +"<br>")
document.write(1 === '1'  +"<br>")